name: Ruby

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby:
          - 3.0.1

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby 3.0
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Lint code
        run: bundle exec rake lint
      - name: Test code
        run: bundle exec rake test
