name: Ruby

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 3.0
        uses: actions/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Lint code
        run: bundle exec rake lint
      - name: Test code
        run: bundle exec rake test
